name: Update CF Data
on:
  schedule:
    - cron: '0 0 * * *' # This runs exactly at 00:00 (Midnight) UTC every day
  workflow_dispatch:      # Allows you to click a button to run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Dependencies
        run: npm install axios
        
      - name: Run Scraper
        run: node generate_list.js
        
      - name: Commit and Push JSON
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update enriched_problems.json"